name: university_companion
description: A comprehensive university services mobile application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  table_calendar: ^3.0.9

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.8.1
  firebase_auth_web: ^5.8.13  # For Web Support

  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2  # ✅ Downgraded to match `ar_flutter_plugin`
  geocoding: ^2.1.1

  # AR & Navigation
  ar_flutter_plugin: ^0.7.3  # Depends on geolocator ^9.0.0

  # Authentication
  google_sign_in: ^6.1.6

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Networking
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  js: ^0.6.4  # ✅ Downgraded to match `connectivity_plus`

  # AI & ML
  google_generative_ai: ^0.4.6

  # Payments
  flutter_stripe: ^9.5.0+1

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  permission_handler: ^10.1.0

  # Voice & Speech
  speech_to_text: ^6.4.1
  flutter_tts: ^3.8.3
  flutter_dotenv: ^5.2.1

  # Notifications
  flutter_local_notifications: ^16.2.0

  # QR & Barcode
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.3.8



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - web/  # 🔥 Added for Web Support

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#4A6572"
  image: assets/images/splash_logo.png
  android: true
  ios: true
